name: flutter_cienmaq
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_swiper_null_safety_flutter3: ^4.0.3
  http: ^1.3.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
   - imaages/review1.png
   - imaages/rates.png
   - imaages/venom.png
   - imaages/pushpa.png
   - imaages/salaar.png
   - imaages/movie.png
   - imaages/eagle.png
   - imaages/sahoo.png
   - imaages/jailer.png
   - imaages/game change.png
   - imaages/daku maharaj.png
   - imaages/ram charan.png
   - imaages/app.png
   - imaages/sp1.png
   - imaages/sp2.png
   - imaages/sp3.png
   - imaages/games.png
   - imaages/paid.png
   - imaages/play.png

